import { ThemeConfig, LinkItem, AnalyticsDataPoint, MetricMilestone } from "./types";

export const THEME_PRESETS: ThemeConfig[] = [
  {
    id: "cosmic",
    name: "Cosmic Charcoal",
    backgroundClass: "bg-slate-950 bg-radial-[circle_at_top_right,_var(--tw-gradient-stops)] from-indigo-950 via-slate-950 to-neutral-950",
    cardBgClass: "bg-slate-900/70 border border-slate-800 backdrop-blur-md",
    textClass: "text-slate-100",
    accentClass: "text-indigo-400 bg-indigo-500/10 border-indigo-500/20",
    buttonClass: "bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-900/30",
    fontFamily: "font-sans",
    borderRadius: "rounded-2xl",
    isDark: true,
  },
  {
    id: "aurora",
    name: "Aurora Sage",
    backgroundClass: "bg-zinc-950 bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))] from-emerald-950/40 via-zinc-950 to-neutral-950",
    cardBgClass: "bg-zinc-900/60 border border-emerald-900/20 backdrop-blur-md",
    textClass: "text-zinc-100",
    accentClass: "text-emerald-400 bg-emerald-500/10 border-emerald-500/15",
    buttonClass: "bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-950/50",
    fontFamily: "font-sans",
    borderRadius: "rounded-xl",
    isDark: true,
  },
  {
    id: "sunset",
    name: "Crimson Sunset",
    backgroundClass: "bg-black bg-radial-[circle_at_center,_var(--tw-gradient-stops)] from-rose-950 via-neutral-950 to-black",
    cardBgClass: "bg-neutral-900/50 border border-rose-900/20 backdrop-blur-md",
    textClass: "text-neutral-100",
    accentClass: "text-rose-400 bg-rose-500/10 border-rose-500/20",
    buttonClass: "bg-gradient-to-r from-rose-600 to-amber-600 hover:from-rose-500 hover:to-amber-500 text-white shadow-lg shadow-rose-950/40",
    fontFamily: "font-sans",
    borderRadius: "rounded-3xl",
    isDark: true,
  },
  {
    id: "nordic",
    name: "Nordic Minimal",
    backgroundClass: "bg-slate-50",
    cardBgClass: "bg-white border border-slate-200/80 shadow-xs",
    textClass: "text-slate-800",
    accentClass: "text-slate-600 bg-slate-150 border-slate-200",
    buttonClass: "bg-slate-900 hover:bg-slate-800 text-white",
    fontFamily: "font-sans",
    borderRadius: "rounded-none",
    isDark: false,
  },
  {
    id: "cyberpunk",
    name: "Cyber Grid",
    backgroundClass: "bg-zinc-950 bg-[linear-gradient(to_right,#1f2937_1px,transparent_1px),linear-gradient(to_bottom,#1f2937_1px,transparent_1px)] bg-[size:4rem_4rem]",
    cardBgClass: "bg-zinc-900 border-2 border-yellow-400 shadow-[4px_4px_0px_0px_#facc15]",
    textClass: "text-zinc-50",
    accentClass: "text-yellow-400 bg-yellow-500/10 border-yellow-400/30",
    buttonClass: "bg-yellow-400 hover:bg-yellow-300 text-black font-mono font-bold tracking-wider uppercase border-2 border-black",
    fontFamily: "font-mono",
    borderRadius: "rounded-none",
    isDark: true,
  },
  {
    id: "editorial",
    name: "Athenaeum Cream",
    backgroundClass: "bg-stone-100 bg-radial-[circle_at_top,_var(--tw-gradient-stops)] from-stone-200/50 via-stone-100 to-stone-50",
    cardBgClass: "bg-stone-50 border border-stone-300/80",
    textClass: "text-stone-900",
    accentClass: "text-amber-800 bg-amber-500/10 border-stone-300",
    buttonClass: "bg-amber-900 hover:bg-amber-800 text-stone-100 border border-amber-950",
    fontFamily: "font-sans",
    borderRadius: "rounded-md",
    isDark: false,
  },
];

export const INITIAL_LINKS: LinkItem[] = [
  {
    id: "link-1",
    title: "🎯 Subscribe on TikTok",
    url: "https://tiktok.com/@growth_hacker",
    platform: "tiktok",
    clickCount: 1420,
    isPublished: true,
    engagementRate: 5.4,
  },
  {
    id: "link-2",
    title: "📸 Watch my Lifestyle Vlogs",
    url: "https://instagram.com/brand_rep",
    platform: "instagram",
    clickCount: 980,
    isPublished: true,
    engagementRate: 4.8,
  },
  {
    id: "link-3",
    title: "💼 Professional Portfolio on LinkedIn",
    url: "https://linkedin.com/in/marketing_expert",
    platform: "linkedin",
    clickCount: 750,
    isPublished: true,
    engagementRate: 6.2,
  },
  {
    id: "link-4",
    title: "🐦 Daily Marketing Nuggets on X",
    url: "https://twitter.com/strategist_x",
    platform: "twitter",
    clickCount: 540,
    isPublished: true,
    engagementRate: 3.9,
  },
  {
    id: "link-5",
    title: "🔍 Connect with me on Peerlist",
    url: "https://peerlist.io/social_leader",
    platform: "peerlist",
    clickCount: 310,
    isPublished: true,
    engagementRate: 5.1,
  },
  {
    id: "link-6",
    title: "💻 Open-source Bio Projects",
    url: "https://github.com/linkify-dev",
    platform: "github",
    clickCount: 420,
    isPublished: true,
    engagementRate: 4.5,
  },
  {
    id: "link-7",
    title: "📩 Email Collaborations",
    url: "mailto:collab@linkify.com?subject=Brand%20Partnership",
    platform: "gmail",
    clickCount: 180,
    isPublished: true,
    engagementRate: 8.9,
  }
];

export const MONTHLY_ANALYTICS: { 
  "7d": AnalyticsDataPoint[];
  "30d": AnalyticsDataPoint[];
  "90d": AnalyticsDataPoint[];
} = {
  "7d": [
    { date: "May 20", clicks: 120, visitors: 95, ctr: 4.1 },
    { date: "May 21", clicks: 145, visitors: 110, ctr: 4.4 },
    { date: "May 22", clicks: 160, visitors: 130, ctr: 4.0 },
    { date: "May 23", clicks: 140, visitors: 105, ctr: 4.3 },
    { date: "May 24", clicks: 190, visitors: 150, ctr: 4.6 },
    { date: "May 25", clicks: 230, visitors: 180, ctr: 4.9 },
    { date: "May 26", clicks: 250, visitors: 200, ctr: 5.2 },
  ],
  "30d": [
    { date: "Apr 27", clicks: 90, visitors: 80, ctr: 3.5 },
    { date: "Apr 30", clicks: 105, visitors: 90, ctr: 3.8 },
    { date: "May 03", clicks: 115, visitors: 100, ctr: 3.6 },
    { date: "May 06", clicks: 130, visitors: 115, ctr: 3.9 },
    { date: "May 09", clicks: 125, visitors: 110, ctr: 4.0 },
    { date: "May 12", clicks: 140, visitors: 120, ctr: 4.1 },
    { date: "May 15", clicks: 165, visitors: 140, ctr: 4.4 },
    { date: "May 18", clicks: 180, visitors: 150, ctr: 4.5 },
    { date: "May 21", clicks: 210, visitors: 170, ctr: 4.8 },
    { date: "May 24", clicks: 245, visitors: 190, ctr: 5.1 },
    { date: "May 26", clicks: 270, visitors: 210, ctr: 5.3 },
  ],
  "90d": [
    { date: "Mar 01", clicks: 65, visitors: 60, ctr: 3.1 },
    { date: "Mar 10", clicks: 75, visitors: 70, ctr: 3.2 },
    { date: "Mar 20", clicks: 80, visitors: 75, ctr: 3.4 },
    { date: "Mar 30", clicks: 95, visitors: 85, ctr: 3.5 },
    { date: "Apr 09", clicks: 110, visitors: 95, ctr: 3.8 },
    { date: "Apr 19", clicks: 125, visitors: 105, ctr: 4.0 },
    { date: "Apr 29", clicks: 135, visitors: 115, ctr: 4.2 },
    { date: "May 09", clicks: 160, visitors: 130, ctr: 4.5 },
    { date: "May 19", clicks: 210, visitors: 170, ctr: 4.9 },
    { date: "May 26", clicks: 280, visitors: 220, ctr: 5.4 },
  ]
};

export const INITIAL_MILESTONES: MetricMilestone[] = [
  {
    id: "m-1",
    metric: "clicks",
    threshold: 1500,
    role: "owner",
    isEnabled: true,
    notified: false,
  },
  {
    id: "m-2",
    metric: "ctr",
    threshold: 6.0,
    role: "manager",
    isEnabled: true,
    notified: false,
  },
  {
    id: "m-3",
    metric: "visitors",
    threshold: 1000,
    role: "editor",
    isEnabled: false,
    notified: false,
  },
];
